In [1]:
# Import Dependencies

import pandas as pd

In [2]:
# Read flash report files for all months for 2019

df1 = pd.read_csv("fr2019/FlashReport_Jan 2019.csv")
df2 = pd.read_csv("fr2019/FlashReport_Feb 2019.csv")
df3 = pd.read_csv("fr2019/FlashReport_Mar 2019.csv")
df4 = pd.read_csv("fr2019/FlashReport_April 2019.csv")
df5 = pd.read_csv("fr2019/FlashReport_May 2019.csv")
df6 = pd.read_csv("fr2019/FlashReport_June 2019.csv")
df7 = pd.read_csv("fr2019/FlashReport_July 2019.csv")
df8 = pd.read_csv("fr2019/FlashReport_Aug 2019.csv")
df9 = pd.read_csv("fr2019/FlashReport_Sept 2019.csv")
df10 = pd.read_csv("fr2019/FlashReport_Oct 2019.csv")
df11 = pd.read_csv("fr2019/FlashReport_Nov 2019.csv")
df12 = pd.read_csv("fr2019/FlashReport_Dec 2019.csv")

In [5]:
# Drop the first row

df1 = df1.drop([0])
df2 = df2.drop([0])
df3 = df3.drop([0])
df4 = df4.drop([0])
df5 = df5.drop([0])
df6 = df6.drop([0])
df7 = df7.drop([0])
df8 = df8.drop([0])
df9 = df9.drop([0])
df10 = df10.drop([0])
df11 = df11.drop([0])
df12 = df12.drop([0])

In [25]:
df12.head()

,Rep Name,PDRs,Leads,Total Leads,Appts,Shows,Enrols,Cancel Enrollment,Starts,CMEs,NMEs,FMEs,PMEs,App Set,Show Rate,(Show To Enrollment),(Enrollment to Start Rate),(Lead to start)
1,Arushi Verma,0,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
2,Charu Manrao,0,3,3.0,1.0,1.0,3.0,0.0,3.0,3.0,0.0,0.0,0.0,33.33%,100.00%,300.00%,100.00%,100.00%
3,Dorota Mirek,0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
4,Emani Knight,0,2,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
5,Guneet Singh,0,40,40.0,24.0,12.0,4.0,0.0,4.0,0.0,2.0,0.0,2.0,60.00%,50.00%,33.33%,100.00%,10.00%

In [26]:
# Drop row with Rep Name="Academy Director"

df2 = df2.drop([1])

In [28]:
df2

,Rep Name,PDRs,Leads,Total Leads,Appts,Shows,Enrols,Cancel Enrollment,Starts,CMEs,NMEs,FMEs,PMEs,App Set,Show Rate,(Show To Enrollment),(Enrollment to Start Rate),(Lead to start)
2,Ankita Laroiya,0,2,2.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,100.00%,50.00%,0.00%,0.00%,50.00%
3,Arushi Verma,0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
4,Barb Sanderson,0,169,169.0,55.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.54%,27.27%,0.00%,0.00%,0.00%
5,Danial Banizamani,0,30,30.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.67%,0.00%,0.00%,0.00%,0.00%
6,Guneet Singh,0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
7,Guneet Singh,0,174,174.0,56.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.18%,28.57%,0.00%,0.00%,0.00%
8,Harit Gaba,0,18,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
9,Jho Borras,0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
10,Manmeet Saini,0,148,148.0,45.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.41%,20.00%,0.00%,0.00%,0.00%
11,Paterno Surigao,0,9,9.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.44%,75.00%,0.00%,0.00%,0.00%
12,Paul Lemieux,0,169,169.0,52.0,13.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,30.77%,25.00%,0.00%,0.00%,0.00%
13,Preet Buttar,0,16,16.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.25%,0.00%,0.00%,0.00%,0.00%
14,Preeti Singh,0,1,1.0,3.0,4.0,0.0,0.0,3.0,0.0,0.0,0.0,2.0,300.00%,133.33%,0.00%,0.00%,300.00%
15,Russ Jude,0,189,189.0,80.0,37.0,0.0,0.0,19.0,0.0,0.0,0.0,16.0,42.33%,46.25%,0.00%,0.00%,10.05%
16,Unknown,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00%,0.00%,0.00%,0.00%,0.00%
17,Total,0,929,929.0,300.0,98.0,1.0,0.0,24.0,0.0,0.0,2.0,19.0,32.29%,32.67%,1.02%,"2,400.00%",2.58%
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Region Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.56%,52.72%,44.13%,114.52%,9.47%
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Territory Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.46%,53.21%,45.30%,113.33%,9.42%
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,National Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.36%,60.63%,55.03%,101.83%,12.35%